In [ ]:
import torch

In [ ]:
x = torch.arange(12,dtype=torch.float16)
print(x.shape)
print(x.reshape(12,1).shape)
print(x.numel())

torch.Size([12])
torch.Size([12, 1])
12


## Indexing and Slicing

Indexed or sliced value shares same data with original tensor, so if you modify it will reflect to original one

In [ ]:
X = x.reshape(3,4)
print(X)
print(X[:,1]) #second column
print(X[-1,:]) #last row
print(X[1]) # second row

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float16)
tensor([1., 5., 9.], dtype=torch.float16)
tensor([ 8.,  9., 10., 11.], dtype=torch.float16)
tensor([4., 5., 6., 7.], dtype=torch.float16)


In [ ]:
T = X[:,2]
print(T)
print(T.shape)

tensor([ 2.,  6., 10.], dtype=torch.float16)
torch.Size([3])


In [ ]:
T[0] = 1000.0
print(X)
# You will see X[0,2] will be 1000
print(X[0,2])

tensor([[   0.,    1., 1000.,    3.],
        [   4.,    5.,    6.,    7.],
        [   8.,    9.,   10.,   11.]], dtype=torch.float16)
tensor(1000., dtype=torch.float16)


**WARN:** `X[start:stop]`, where
**the returned value includes the first index (start) but not the last (stop).**

#Broadcasting

In [ ]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))

a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [ ]:
a + b  # must be (3,2)

tensor([[0, 1],
        [1, 2],
        [2, 3]])

Two tensors are “broadcastable” if the following rules hold:

- Each tensor has at least one dimension.
- When iterating over the dimension sizes, starting at the trailing dimension, the dimension sizes must **either be equal, one of them is 1, or one of them does not exist.**

Best way to save memory is to use in-place operations, let's show with `id()` function which shows memory address of the object

In [ ]:
X = torch.arange(12,dtype=torch.bfloat16).reshape(3,4)
Y = torch.ones_like(X)
print(X,Y)
print(f'Memory address of X: {id(X)}')
print(f'Memory address of Y: {id(Y)}')

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.bfloat16) tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.bfloat16)
Memory address of X: 132374725402960
Memory address of Y: 132374725404784


In [ ]:
Z = X + Y
print(id(Z))

132374900591024


In [ ]:
# We can directly change the data in X
X[:] = X + Y
# Or X += Y

# Linear Algebra

In [ ]:
# Show that transpose of transpose equal to original matrix
A= torch.arange(12,dtype=torch.float32).reshape(3,4)
B = A.T
torch.equal(A,B.T)

True

In [ ]:
#We defined the tensor X of shape (2, 3, 4) in this section. What is the output of len(X)?
X = torch.ones((2,3,4))
len(X) # 2

2